const diseaseDefault = [
    {
      "id": 1,
      "stage": "thrips",
      "title": "Héo Úa Vàng",
      "description": "Hạt giống cây ớt bắt đầu nảy mầm sau khi được gieo và tưới nước đủ.",
      "minTempurature": 25,
      "maxTempurature": 30,
      "minHumidity": 70,
      "maxHumidity": 80,
      "minLight": 5000,
      "maxLight": 5000,
      "days": 0,
    },
    {
      "id": 2,
      "stage": "virus kuning",
      "title": "Đóm lá vi khuẩn",
      "description": "Cây ớt phát triển đến khi có 2 lá mầm đầu tiên.",
      "minTempurature": 18,
      "maxTempurature": 20,
      "minHumidity": 80,
      "maxHumidity": 80,
      "minLight": 5000,
      "maxLight": 5000,
      "days": 9,
    },
    {
      "id": 3,
      "stage": "bercak daun",
      "title": "Bọ trĩ",
      "description": "Phát triển đến 4-6 lá thật, cây phát triển rễ và bắt đầu sử dụng dinh dưỡng từ bên ngoài",
      "minTempurature": 18,
      "maxTempurature": 20,
      "minHumidity": 80,
      "maxHumidity": 80,
      "minLight": 5000,
      "maxLight": 5000,
      "days": 40,
    },
]
export default diseaseDefault;