const stageDefault = [
      {
        "id": 1,
        "stage": "Planting",
        "description": "Hạt giống cây ớt bắt đầu nảy mầm sau khi được gieo và tưới nước đủ.",
        "minTempurature": 25,
        "maxTempurature": 30,
        "minHumidity": 70,
        "maxHumidity": 80,
        "minLight": 80,
        "maxLight": 95,
        "days": 0,
      },
      {
        "id": 2,
        "stage": "Germination",
        "description": "Cây ớt phát triển đến khi có 2 lá mầm đầu tiên.",
        "minTempurature": 18,
        "maxTempurature": 20,
        "minHumidity": 80,
        "maxHumidity": 80,
        "minLight": 80,
        "maxLight": 95,
        "days": 9,
      },
      {
        "id": 3,
        "stage": "Seedling",
        "description": "Phát triển đến 4-6 lá thật, cây phát triển rễ và bắt đầu sử dụng dinh dưỡng từ bên ngoài",
        "minTempurature": 18,
        "maxTempurature": 20,
        "minHumidity": 80,
        "maxHumidity": 80,
        "minLight": 80,
        "maxLight": 95,
        "days": 40,
      },
      {
        "id": 4,
        "stage": "Green Anise",
        "description": "Cây ớt bắt đầu ra những bông hoa đầu tiên, báo hiệu sắp có trái.",
        "minTempurature": 18,
        "maxTempurature": 20,
        "minHumidity": 80,
        "maxHumidity": 80,
        "minLight": 80,
        "maxLight": 95,
        "days": 47,
      },
      {
        "id": 5,
        "stage": "Branching",
        "description": "Hoa của cây ớt bắt đầu đậu trái sau khi thụ phấn.",
        "minTempurature": 18,
        "maxTempurature": 20,
        "minHumidity": 80,
        "maxHumidity": 80,
        "minLight": 80,
        "maxLight": 95,
        "days": 65,
      },
      {
        "id": 6,
        "stage": "Flowering",
        "description": "Quả ớt chín và sẵn sàng để thu hoạch.",
        "minTempurature": 20,
        "maxTempurature": 25,
        "minHumidity": 80,
        "maxHumidity": 90,
        "minLight": 80,
        "maxLight": 95,
        "days": 85,
      },
      {
        "id": 7,
        "stage": "Fruit",
        "description": "Quả ớt chín và sẵn sàng để thu hoạch.",
        "minTempurature": 20,
        "maxTempurature": 25,
        "minHumidity": 80,
        "maxHumidity": 90,
        "minLight": 80,
        "maxLight": 95,
        "days": 100,
      },
      {
        "id": 8,
        "stage": "Rippen & First Harvest",
        "description": "Quả ớt chín và sẵn sàng để thu hoạch.",
        "minTempurature": 20,
        "maxTempurature": 25,
        "minHumidity": 80,
        "maxHumidity": 90,
        "minLight": 80,
        "maxLight": 95,
        "days": 140,
      },
      {
        "id": 9,
        "stage": "Rippen & Second Harvest",
        "description": "Quả ớt chín và sẵn sàng để thu hoạch.",
        "minTempurature": 20,
        "maxTempurature": 25,
        "minHumidity": 80,
        "maxHumidity": 90,
        "minLight": 80,
        "maxLight": 95,
        "days": 200,
      },
      {
        "id": 10,
        "stage": "Final",
        "description": "Quả ớt chín và sẵn sàng để thu hoạch.",
        "minTempurature": 20,
        "maxTempurature": 25,
        "minHumidity": 80,
        "maxHumidity": 90,
        "minLight": 80,
        "maxLight": 95,
        "days": 200,
      },
]
export default stageDefault;